freebsd_instance:
  image_family: freebsd-14-2

env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_build_task:
  name: "FreeBSD Build"
  install_script:
    - pkg install -y cmake
  build_script:
    - cmake -S . -B build
    - cmake --build build

freebsd_test_task:
  name: "FreeBSD Tests"
  install_script:
    - pkg install -y cmake
  build_script:
    - cmake -S . -B build
    - cmake --build build
  test_script:
    - SINTRA_TRACE_SYNC=1 SINTRA_TRACE_SCOPE="managed.*,swarm.*,spawn.*,reader.*,branch.*,barrier.*,test.*,coordinator.*,rpc.*" \
      ctest --test-dir build --output-on-failure -R sintra.basic_pubsub
