name: Build - macOS

on:
  push:
    branches: [ '*' ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'third_party/**'
      - 'tests/**'
      - 'example/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'third_party/**'
      - 'tests/**'
      - 'example/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode toolchain with sys/ulock.h
        id: macos-sdk
        run: |
          set -euo pipefail

          if ! command -v xcode-select >/dev/null; then
            echo "::error::xcode-select not available" >&2
            exit 1
          fi

          selected=""
          sdkroot=""
          found_any=0
          declare -a candidate_dirs=()

          current_dir="$(xcode-select -p 2>/dev/null || true)"
          if [ -n "$current_dir" ]; then
            candidate_dirs+=("$current_dir")
          fi

          if [ -d /Applications ]; then
            while IFS= read -r app; do
              developer_dir="$app/Contents/Developer"
              if [ -d "$developer_dir" ]; then
                candidate_dirs+=("$developer_dir")
              fi
            done < <(find /Applications -maxdepth 1 -type d -name 'Xcode*.app' -print | sort -r)
          fi

          if [ -d /Library/Developer/CommandLineTools ]; then
            candidate_dirs+=("/Library/Developer/CommandLineTools")
          fi

          if [ ${#candidate_dirs[@]} -eq 0 ]; then
            echo "::error::No candidate developer directories found" >&2
            exit 1
          fi

          while IFS= read -r developer_dir; do
            found_any=1
            if SDKROOT="$(DEVELOPER_DIR="$developer_dir" xcrun --sdk macosx --show-sdk-path 2>/dev/null)"; then
              if [ -f "$SDKROOT/usr/include/sys/ulock.h" ]; then
                selected="$developer_dir"
                sdkroot="$SDKROOT"
                break
              else
                echo "Skipping $developer_dir: sys/ulock.h not found in $SDKROOT" >&2
              fi
            else
              echo "Skipping $developer_dir: unable to determine macOS SDK" >&2
            fi
          done < <(printf '%s\n' "${candidate_dirs[@]}" | awk '!seen[$0]++')

          if [ "$found_any" -eq 0 ]; then
            echo "::error::No developer directories evaluated" >&2
            exit 1
          fi

          if [ -z "$selected" ] || [ -z "$sdkroot" ]; then
            echo "::error::None of the installed Xcode toolchains provide sys/ulock.h" >&2
            exit 1
          fi

          echo "Selecting $selected"
          if [ "$(xcode-select -p 2>/dev/null || true)" != "$selected" ]; then
            sudo xcode-select --switch "$selected"
          fi
          xcode-select -p
          echo "Found sys/ulock.h in $sdkroot"

          echo "developer_dir=$selected" >> "$GITHUB_OUTPUT"
          echo "sdkroot=$sdkroot" >> "$GITHUB_OUTPUT"

      - name: Export developer dir
        if: ${{ steps.macos-sdk.outputs.developer_dir != '' }}
        run: echo "DEVELOPER_DIR=${{ steps.macos-sdk.outputs.developer_dir }}" >> "$GITHUB_ENV"

      - name: Detect changed areas
        id: changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - 'src/**'
              - 'include/**'
              - 'cmake/**'
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
              - 'third_party/**'
            tests:
              - 'tests/**'
            examples:
              - 'example/**'
            workflows:
              - '.github/workflows/**'

      - name: Compute CMake flags
        id: flags
        shell: bash
        run: |
          CT="-DSINTRA_BUILD_TESTS=OFF -DSINTRA_TEST_MATRIX=quick"
          CE="-DSINTRA_BUILD_EXAMPLES=OFF"
          CS="-DSINTRA_RELEASE_WITH_DEBUG_SYMBOLS=ON"
          if [ "${{ steps.changed.outputs.tests }}" = "true" ] || [ "${{ steps.changed.outputs.core }}" = "true" ] || [ "${{ steps.changed.outputs.workflows }}" = "true" ]; then
            CT="-DSINTRA_BUILD_TESTS=ON -DSINTRA_TEST_MATRIX=quick"
          fi
          if [ "${{ steps.changed.outputs.examples }}" = "true" ]; then
            CE="-DSINTRA_BUILD_EXAMPLES=ON"
          fi
          echo "CMAKE_FLAGS=$CT $CE $CS" >> "$GITHUB_OUTPUT"

      - name: Verify LLDB availability
        env:
          DEVELOPER_DIR: ${{ steps.macos-sdk.outputs.developer_dir }}
        run: |
          if ! xcrun -f lldb >/dev/null 2>&1; then
            echo "::error::lldb not available via xcrun. Install Xcode Command Line Tools to provide LLDB." >&2
            exit 1
          fi
          xcrun lldb --version

      - name: Configure CMake
        env:
          SDKROOT: ${{ steps.macos-sdk.outputs.sdkroot }}
          DEVELOPER_DIR: ${{ steps.macos-sdk.outputs.developer_dir }}
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release ${{ steps.flags.outputs.CMAKE_FLAGS }}

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.core == 'true' || steps.changed.outputs.workflows == 'true'
        run: ctest --test-dir build -C Release --output-on-failure --timeout 60

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ github.event.pull_request.head.sha || github.sha }}
          path: build/
          retention-days: 1
