name: Build - Windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Windows debugging tools
        shell: pwsh
        run: |
          choco install windows-sdk-10 --no-progress -y --package-parameters "'ADDLOCAL=DebuggingTools'"
          $debugDirs = @(
            "${env:ProgramFiles(x86)}\Windows Kits\10\Debuggers\x64",
            "${env:ProgramFiles(x86)}\Windows Kits\10\Debuggers\x86"
          ) | Where-Object { $_ -and (Test-Path $_) }
          if (-not $debugDirs) {
            throw 'Windows debugging tools not found after installation.'
          }
          foreach ($dir in $debugDirs) {
            Add-Content -Path $env:GITHUB_PATH -Value $dir
          }

      - name: Verify Windows debuggers
        shell: pwsh
        run: |
          $candidates = @('cdb', 'ntsd', 'windbg')
          $found = @()
          foreach ($candidate in $candidates) {
            try {
              $paths = (where.exe $candidate 2>$null)
              if ($paths) {
                Write-Host "$candidate -> $paths"
                $found += $candidate
              } else {
                Write-Warning "Unable to locate $candidate"
              }
            } catch {
              Write-Warning "Unable to locate $candidate"
            }
          }
          if (-not $found) {
            throw "No Windows debugger discovered. Checked: $($candidates -join ', ')"
          }

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.event.pull_request.head.sha || github.sha }}
          path: build/
          retention-days: 1
