name: Build - Windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Windows debugging tools
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          choco install --yes --no-progress windows-sdk-10-version-10.0.22621.0 --package-parameters "'ADDLOCAL=DebuggingTools'"

          $debugToolsRoot = Join-Path "${env:ProgramFiles(x86)}" 'Windows Kits\10\Debuggers'
          $candidatePaths = @(
            Join-Path $debugToolsRoot 'x64',
            Join-Path $debugToolsRoot 'x86',
            Join-Path $debugToolsRoot 'arm64'
          ) | Where-Object { Test-Path $_ }

          foreach ($candidate in $candidatePaths) {
            Add-Content -Path $env:GITHUB_PATH -Value $candidate
          }

      - name: Verify Windows debuggers
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $debuggers = @('cdb', 'ntsd', 'windbg')
          $found = @()
          foreach ($debugger in $debuggers) {
            $command = Get-Command $debugger -ErrorAction SilentlyContinue
            if ($command) {
              $found += "$debugger -> $($command.Source)"
            }
          }

          if (-not $found) {
            throw 'None of the Windows debugging tools (cdb, ntsd, windbg) were found in PATH after installation.'
          }

          $found | ForEach-Object { Write-Host $_ }

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.event.pull_request.head.sha || github.sha }}
          path: build/
          retention-days: 1
