name: Build - macOS

on:
  push:
    branches: [ '*' ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'third_party/**'
      - 'tests/**'
      - 'example/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'src/**'
      - 'include/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'third_party/**'
      - 'tests/**'
      - 'example/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Build
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed areas
        id: changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            core:
              - 'src/**'
              - 'include/**'
              - 'cmake/**'
              - 'CMakeLists.txt'
              - 'CMakePresets.json'
              - 'third_party/**'
            tests:
              - 'tests/**'
            examples:
              - 'example/**'
            workflows:
              - '.github/workflows/**'

      - name: Compute CMake flags
        id: flags
        shell: bash
        run: |
          CT="-DSINTRA_BUILD_TESTS=OFF -DSINTRA_TEST_MATRIX=quick"
          CE="-DSINTRA_BUILD_EXAMPLES=OFF"
          CS="-DSINTRA_RELEASE_WITH_DEBUG_SYMBOLS=ON"
          if [ "${{ steps.changed.outputs.tests }}" = "true" ] || [ "${{ steps.changed.outputs.core }}" = "true" ] || [ "${{ steps.changed.outputs.workflows }}" = "true" ]; then
            CT="-DSINTRA_BUILD_TESTS=ON -DSINTRA_TEST_MATRIX=quick"
          fi
          if [ "${{ steps.changed.outputs.examples }}" = "true" ]; then
            CE="-DSINTRA_BUILD_EXAMPLES=ON"
          fi
          echo "CMAKE_FLAGS=$CT $CE $CS" >> "$GITHUB_OUTPUT"

      - name: Verify LLDB availability
        run: |
          if ! xcrun -f lldb >/dev/null 2>&1; then
            echo "::error::lldb not available via xcrun. Install Xcode Command Line Tools to provide LLDB." >&2
            exit 1
          fi
          xcrun lldb --version

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release ${{ steps.flags.outputs.CMAKE_FLAGS }}

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.core == 'true' || steps.changed.outputs.workflows == 'true'
        run: ctest --test-dir build -C Release --output-on-failure --timeout 60

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-${{ github.event.pull_request.head.sha || github.sha }}
          path: build/
          retention-days: 1

  stress-tests:
    name: Stress tests - macOS
    needs: build
    if: ${{ needs.build.result == 'success' }}
    uses: ./.github/workflows/stress-test-macos.yml
    secrets: inherit
    with:
      build_run_id: ${{ github.run_id }}
      head_sha: ${{ github.event.pull_request.head.sha || github.sha }}
      base_sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
      branch: ${{ github.head_ref || github.ref_name }}
      pr_number: ${{ github.event.pull_request.number || '' }}
