name: Build - Windows

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Windows debugging tools
        shell: pwsh
        run: |
          $debugTools = "${env:ProgramFiles(x86)}\Windows Kits\10\Debuggers\x64"
          if (-not (Test-Path $debugTools)) {
            choco install --no-progress windows-sdk-10-version-10.0.22621.0 --package-parameters "'ADDLOCAL=DebuggingTools'"
          }
          Add-Content -Path $env:GITHUB_PATH -Value $debugTools

      - name: Verify Windows debuggers
        shell: pwsh
        run: |
          $tools = @('cdb', 'ntsd', 'windbg')
          $found = @()
          foreach ($tool in $tools) {
            $command = Get-Command $tool -ErrorAction SilentlyContinue
            if ($command) {
              Write-Host "$tool found at $($command.Source)"
              $found += $command
            }
          }
          if (-not $found) {
            throw "No Windows debugger (cdb, ntsd, windbg) found in PATH"
          }

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.event.pull_request.head.sha || github.sha }}
          path: build/
          retention-days: 1
