name: Stress Test - Windows (trigger)

on:
  workflow_run:
    workflows: ["Build - Windows"]
    types:
      - completed

jobs:
  stress-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/stress-test-windows.yml
    secrets: inherit
    with:
      build_run_id: ${{ github.event.workflow_run.id }}
      head_sha: ${{ github.event.workflow_run.head_sha }}
      base_sha: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].base.sha || '' }}
      branch: ${{ github.event.workflow_run.head_branch }}
      pr_number: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].number || '' }}
