name: Stress Test - Linux
run-name: Stress Test - ${{ github.event.workflow_run.display_title }}

on:
  workflow_run:
    workflows: ["Build - Linux"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  stress-test:
    name: Stress Test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-${{ github.event.workflow_run.head_sha }}
          path: build/
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
          if-no-artifact-found: error

      - name: Read change summary
        id: changed
        shell: bash
        run: |
          file="build/changed-areas.env"
          core=false
          tests=false
          examples=false
          workflows=false
          if [ -f "$file" ]; then
            while IFS='=' read -r name value; do
              case "$name" in
                core) core="$value" ;;
                tests) tests="$value" ;;
                examples) examples="$value" ;;
                workflows) workflows="$value" ;;
              esac
            done < "$file"
          fi
          echo "core=$core" >> "$GITHUB_OUTPUT"
          echo "tests=$tests" >> "$GITHUB_OUTPUT"
          echo "examples=$examples" >> "$GITHUB_OUTPUT"
          echo "workflows=$workflows" >> "$GITHUB_OUTPUT"

      - name: Restore cached gdb toolchain
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        id: cache-gdb
        uses: actions/cache@v4
        with:
          path: ~/.cache/sintra-gdb
          key: linux-gdb-${{ runner.os }}-v2024-04-03

      - name: Bootstrap gdb toolchain cache
        if: (steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true') && steps.cache-gdb.outputs.cache-hit != 'true'
        run: |
          set -euxo pipefail
          cache_root="$HOME/.cache/sintra-gdb"
          rm -rf "$cache_root"
          mkdir -p "$cache_root/debs" "$cache_root/root"
          sudo rm -f /var/cache/apt/archives/*.deb
          sudo apt-get update
          sudo apt-get install -y --download-only gdb
          sudo cp /var/cache/apt/archives/*.deb "$cache_root/debs/"
          sudo chown -R "$(id -u)":"$(id -g)" "$cache_root"
          shopt -s nullglob
          for deb in "$cache_root"/debs/*.deb; do
            dpkg-deb -x "$deb" "$cache_root/root"
          done
          sudo apt-get clean

      - name: Activate cached gdb toolchain
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        run: |
          set -euxo pipefail
          cache_prefix="$HOME/.cache/sintra-gdb/root"
          echo "$cache_prefix/usr/bin" >> "$GITHUB_PATH"
          lib_paths=(
            "$cache_prefix/usr/lib/x86_64-linux-gnu"
            "$cache_prefix/usr/lib"
            "$cache_prefix/lib/x86_64-linux-gnu"
            "$cache_prefix/lib"
          )
          ld_path="$(IFS=:; echo "${lib_paths[*]}")"
          if [ -n "${LD_LIBRARY_PATH:-}" ]; then
            ld_path="$ld_path:$LD_LIBRARY_PATH"
          fi
          echo "LD_LIBRARY_PATH=$ld_path" >> "$GITHUB_ENV"

      - name: Allow ptrace attachments for crash debugging
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        run: |
          sudo sysctl -w kernel.yama.ptrace_scope=0

      - name: Verify ptrace scope
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        run: sysctl kernel.yama.ptrace_scope

      - name: Verify gdb
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        run: gdb --version

      - name: Setup Python
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Make test executables executable
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        shell: bash
        run: |
          if [ -d build/tests ]; then
            find build/tests -type f -exec chmod +x {} +
          fi

      - name: Run stress tests with run_tests.py
        if: steps.changed.outputs.tests == 'true' || steps.changed.outputs.workflows == 'true'
        shell: bash
        run: |
          cd tests
          python run_tests.py --repetitions 10 --timeout 30 --build-dir ../build --config Release
